"use client";

import { publicDraftResearch, researchSources } from "./draftResearch";
import { leagueWinnerResearch } from "./leagueWinners";

export function DraftIntelligenceMethodology({ scoringLabel }: { scoringLabel: string }) {
  return <section className="method-panel keeper-score-method">
    <div className="method-panel-heading"><div><p className="eyebrow">FLOCK · BORIS · LIVE HEALTH · LEAGUE VALUE · STRATEGY · MONTE CARLO · UPSIDE</p><h3>How the decision layer works</h3></div><p>Flock, current consensus, Boris tiers, projections, health, strategy, and source-tagged upside remain separately auditable. The final rank does not overwrite your personal Like/Avoid/Diamond decisions.</p></div>
    <div className="formula-line">League rank = 82% verified market/opinion layer + 18% league value-over-replacement rank · expected PPG = healthy projection × availability ÷ 17</div>
    <div className="method-weight-grid">
      <article><b>FLOCK</b><h4>Cross-position opinion anchor</h4><code>78% Flock + 22% current consensus → market layer</code><p>The Top 100 supplies the baseline. The newer Top 50 WR video replaces only the older relative WR order; dated riser/faller signals are modest adjustments after their injury or depth-chart premise is checked against newer reporting.</p></article>
      <article><b>BORIS</b><h4>Official tier source</h4><code>FantasyPros Avg.Rank → Gaussian mixture clusters</code><p>The updater imports Boris Chen&apos;s published position and overall CSV exports. “Boris tier” is preserved exactly as published; it is never rewritten by this site&apos;s injury layer.</p></article>
      <article><b>LIVE</b><h4>Injury-aware ordering</h4><code>market layer + dated status penalty → re-sort</code><p>ESPN status is the baseline. A dated repository override is used only when a newer report is more specific. League rank and live tier move; consensus, Flock rank, and Boris tier remain alongside them for auditability.</p></article>
      <article><b>ROOM</b><h4>League recalculation</h4><code>scoring + teams + starters + FLEX + bench → replacement PPG</code><p>{scoringLabel} gets its own replacement pool. Deep 14-team rooms, shallow 10-team rooms, extra FLEX spots, half/full PPR, and bench depth therefore change positional scarcity and final rank.</p></article>
      <article><b>PPG</b><h4>Two weekly views</h4><code>expected PPG = adjusted season total ÷ 17</code><p>Expected PPG spreads missed games across the full fantasy season and drives plans. Active-game PPG keeps the healthy per-game estimate visible, which separates availability risk from on-field ceiling.</p></article>
      <article><b>A–J</b><h4>Ten strategic paths</h4><code>PPG + VORP + price + tier + roster need + profile</code><p>Each plan estimates who can still reach the user&apos;s snake pick, scores injury-adjusted weekly production and value over replacement, then applies one strategic profile such as Hero RB, WR Avalanche, elite QB/TE, Zero RB, or Late QB.</p></article>
      <article><b>GUARD</b><h4>Roster construction</h4><code>hard caps + deadlines + early-round balance</code><p>The optimizer blocks duplicate specialists, delays K/D/ST, prevents extreme early position overload, and forces missing QB, TE, RB, WR, K, and D/ST slots before the draft ends.</p></article>
      <article><b>VALUE</b><h4>Plan scorecards</h4><code>starter PPG · roster PPG · value · construction</code><p>Starter PPG is the best legal weekly lineup. Value compares ADP with the league-model cost, while the player drawer retains the consensus comparison. Construction reports whether every starter and FLEX can be filled; these are decision aids, not season-win probabilities.</p></article>
      <article><b>MC</b><h4>Opportunity-cost engine</h4><code>4 candidates × 800 complete draft continuations</code><p>In the Row Fast Eat Ass live and mock boards, every on-clock choice receives 3,200 matched hard-CPU simulations. The engine ranks full-roster utility from starter VORP, depth VORP, construction, and acquisition value; it also exposes the floor, median, ceiling, branch-win rate, and most common players at the next user pick.</p></article>
      <article><b>INTEL</b><h4>Evidence-weighted public research</h4><code>A: 1.00 · B+: .85 · B: .70 · C: .35 · D: .15</code><p>Targets receive only a modest score boost, scaled by evidence quality and league fit. Final-round and deep-only signals are penalized before the late phase; WATCH, INJURY HOLD, and AVOID HYPE reduce recommendations until stronger role or health evidence arrives.</p></article>
      <article><b>SLOT</b><h4>Headliners strategy prior</h4><code>slot group + R5 balance + QB/TE timing + closing rounds</code><p>The user-supplied Fantasy Football Headliners transcript supplies small, soft position bonuses: slot-aware opening preferences, a roughly 3 RB / 2 WR Round-5 target, value-based QB/TE fills in Rounds 6–10, and league-length-aware D/ST, K, and lottery-ticket timing. A stronger live tier, keeper, or points result can override it.</p></article>
      <article><b>WIN</b><h4>Price-sensitive League Winner signal</h4><code>25% price VORP + 20% role growth + 15% ceiling + 15% efficiency + 10% offense + 10% durability + 5% market</code><p>Thirteen orange flags now combine the supplied Headliners transcript with five model-selected candidates supported by current public research. The ceiling component uses the 80th-percentile Monte Carlo outcome, not the median projection. The label is not a guarantee, a replacement for rank/ADP, or an automatic Like; personal Avoid, high injury risk, confirmed keepers, and roster rules retain priority.</p></article>
      <article><b>◆</b><h4>NYFL potential-diamond score</h4><code>30% future role + 25% keeper leverage + 20% prospect + 15% current path + 10% durability</code><p>Young, inexpensive players with a plausible 2027 role and Round 10–16 acquisition cost receive a late-round NYFL planning boost. The 0–100 research score is a keeper-upside triage tool—not a probability of becoming Puka Nacua or Brock Bowers.</p></article>
      <article><b>FRESH</b><h4>Promotion and staleness rules</h4><code>injury 24h · route 72h · ADP daily</code><p>{publicDraftResearch.promotionRule} Reddit is discovery/sentiment only and never counts as verified role evidence by itself.</p></article>
    </div>
    <p className="scoring-caveat"><b>Precedence:</b> hard roster and availability rules → your personal Avoid/Like tags and high injury risk → current price and projections → modest source research adjustments, including League Winner. A player with zero expected availability is excluded. Public research never auto-tags a player as yours and never guarantees an outcome.</p>
    <div className="reference-links"><a href="https://www.youtube.com/watch/73nq-Q6bRyw" target="_blank" rel="noreferrer">Flock Top 100 ↗</a><a href="https://www.youtube.com/watch/X1lFeeBDPCk" target="_blank" rel="noreferrer">Newer WR Top 50 ↗</a><a href="https://www.youtube.com/watch?v=-a3vvqeBKCM" target="_blank" rel="noreferrer">Headliners draft strategy ↗</a><a href={leagueWinnerResearch.source.url} target="_blank" rel="noreferrer">Headliners League Winners ↗</a><a href="https://www.nfl.com/news/2026-nfl-fantasy-football-top-10-league-winners" target="_blank" rel="noreferrer">NFL League Winners ↗</a><a href="https://www.nfl.com/news/2026-nfl-fantasy-football-breakout-candidates-at-qb-rb-wr-and-te" target="_blank" rel="noreferrer">NFL breakout candidates ↗</a><a href="https://www.nbcsports.com/fantasy/football/player-news/2026-08-11/tuten-c-rod-listed-as-co-starters-on-depth-chart" target="_blank" rel="noreferrer">Tuten role report ↗</a><a href="https://www.fantasyalarm.com/articles/nfl/running-backs/seahawks-running-back-depth-chart-2026-fantasy-football/194667" target="_blank" rel="noreferrer">Seattle RB depth chart ↗</a><a href="https://www.nfl.com/news/2026-nfl-fantasy-football-six-late-round-sleepers-to-target" target="_blank" rel="noreferrer">NFL late-round sleepers ↗</a><a href="https://www.fantasypros.com/2026/08/2026-fantasy-football-late-round-draft-strategy/" target="_blank" rel="noreferrer">FantasyPros late strategy ↗</a><a href="https://www.borischen.co/p/draft-kit.html" target="_blank" rel="noreferrer">Boris Chen methodology ↗</a><a href="https://s3-us-west-1.amazonaws.com/fftiers/out/weekly-ALL-PPR.csv" target="_blank" rel="noreferrer">Official published tier exports ↗</a></div>
    <details className="research-source-library"><summary>Open the {researchSources.length}-source public research library</summary><div>{researchSources.map((source) => <a href={source.url} target="_blank" rel="noreferrer" key={source.id}><b>{source.id} · {source.publisher}</b><span>{source.title}</span><small>{source.published} · {source.type}</small></a>)}</div></details>
  </section>;
}
